### ISSUE TITLE
libssh2.so not properly detected on non-amd64 architectures

### ISSUE THREAD

**Issue by rhertzog** [jmk-foofus/medusa#11]
The configure script does not properly detect the presence of libssh2.so on non-amd64 architectures. It only checks a fixed list of path... instead it should check all the directories that the linker is using.

I have found a way to extract that list of directories with the following code snippet:
```ld --verbose | grep SEARCH_DIR | sed -e 's/\"); */\n/g' | cut -d= -f2```

I have a working patch here:
http://git.kali.org/gitweb/?p=packages/medusa.git;a=blob_plain;f=debian/patches/fix-libssl2-configure-check.patch;hb=refs/heads/kali/master

This bug has been first reported to Kali here: https://bugs.kali.org/view.php?id=3126

**Comment by jmk-foofus** [comment]
Thanks! I've applied this patch.
