### ISSUE TITLE
segmentation fault using web-form module

### ISSUE THREAD

**Issue by ghost** [jmk-foofus/medusa#14]
I get a segmentation fault when trying to use the web-form module

medusa -h 127.0.0.1 -u foo -p bar -M web-form -m FORM:"/mutillidae/index.php?page=login.php" -m FORM-DATA:"post?username=&password=&login-php-submit-button=Login"

**Comment by fantomaster** [comment]
Woops. here is the error.

# medusa -h 127.0.0.1 -u foo -p bar -M web-form -m FORM:"/mutillidae/index.php?page=login.php" -m FORM-DATA:"post?username=&password=&login-php-submit-button=Login"
Segmentation fault

**Comment by zume2020** [comment]
Am also gettig the same while running Medusa v2.1.1
`medusa -h localhost -u sumithran@india.com -p 123456789 -M web-form -m FORM:"/CManager/login.php" -m FORM-DATA:"post?email=&pass=&submit=True"`

> Medusa v2.1.1 [http://www.foofus.net] (C) JoMo-Kun / Foofus Networks <jmk@foofus.net>
> 
> Segmentation fault

**Comment by acayusantos** [comment]
this bug 
zsh: segmentation fault  medusa -h

**Comment by jmk-foofus** [comment]
Closing as pull request had been merged.
