### ISSUE TITLE
Add Cygwin support

### ISSUE THREAD

**Issue by vanhauser-thc** [jmk-foofus/medusa#20]
$ autoconf
$ ./configure
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2005-03-24, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2005-03-24

uname -m = x86_64
uname -r = 2.8.0(0.309/5/3)
uname -s = CYGWIN_NT-6.1
uname -v = 2017-04-01 20:47

/usr/bin/uname -p = unknown
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              = x86_64
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = x86_64
UNAME_RELEASE = 2.8.0(0.309/5/3)
UNAME_SYSTEM  = CYGWIN_NT-6.1
UNAME_VERSION = 2017-04-01 20:47
configure: error: cannot guess build type; you must specify one

When I do (its x64 cygwin):
$ ./configure --build=i686-pc-linux-gnu
(lots of stuff)
$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /prg/tmp/medusa/missing aclocal-1.15
 cd . && /bin/sh /prg/tmp/medusa/missing automake-1.15 --gnu
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake-1.15 line 3936.
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /prg/tmp/medusa/missing autoconf
/bin/sh ./config.status --recheck
running CONFIG_SHELL=/bin/sh /bin/sh ./configure --build=i686-pc-linux-gnu --target=i686-pc-linux-gnu build_alias=i686-pc-linux-gnu target_alias=i686-pc-linux-gnu --no-create --no-recursion
[...]
gcc  -g -O2 -fPIC  -L/usr/local/lib -L/usr//lib -rdynamic  -o cvs.mod.exe cvs.o ../medusa-trace.o -lsvn_client-1 -shared -lcrypto -ldl -lpthread  -lssl -lcrypto -lssl -lcrypto -ldl -lrt -lm
cvs.o: In function `tryLogin':
/prg/tmp/medusa/src/modsrc/cvs.c:325: undefined reference to `medusaSend'
/prg/tmp/medusa/src/modsrc/cvs.c:325:(.text+0x4b0): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `medusaSend'
/prg/tmp/medusa/src/modsrc/cvs.c:332: undefined reference to `medusaReceiveRaw'
/prg/tmp/medusa/src/modsrc/cvs.c:332:(.text+0x4cd): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `medusaReceiveRaw'
/prg/tmp/medusa/src/modsrc/cvs.c:361: undefined reference to `setPassResult'
/prg/tmp/medusa/src/modsrc/cvs.c:361:(.text+0x521): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `setPassResult'
cvs.o: In function `initModule':

keep up the great work

**Comment by jmk-foofus** [comment]
The Medusa modules do not build with Cygwin. I've never had a need for this, so I don't see it ever becoming a priority for me. However, I'm certainly open to patches.
