### ISSUE TITLE
Segmentation fault arise on use rdp brute module

### ISSUE THREAD

**Issue by zonadu** [jmk-foofus/medusa#22]
command:
`medusa -M rdp -m DOMAIN:CORPNAME -h 172.24.243.71 -n 3389 -u administrator -P pass.txt`

pass.txt is a password dict, it have 1000+ record.

when i execute this command, an Segmentation fault error occurred, and this error will be occurred when i execute this command every time.

error info:
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
ACCOUNT CHECK: [rdp] Host: 172.24.243.71 (1 of 1, 0 complete) User: administrator (1 of 1, 0 complete) Password: freepass (1000 of 1004 complete)
connected to 172.24.243.71:3389
SSL_read: Failure in SSL library (protocol error?)
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
ACCOUNT CHECK: [rdp] Host: 172.24.243.71 (1 of 1, 0 complete) User: administrator (1 of 1, 0 complete) Password: admin@123456 (1001 of 1004 complete)
connected to 172.24.243.71:3389
Segmentation fault

**Comment by jmk-foofus** [comment]
This is hopefully resolved with recent commits. If not, I'd need more information to reproduce.
