### ISSUE TITLE
dont know what module to use and get error!

### ISSUE THREAD

**Issue by jamieduk** [jmk-foofus/medusa#24]
I get error

jay@JNET ~/Documents/Scripts/Medusa $ medusa -H target_ips.txt -U usernames.txt -P passwords.txt -M [ smbnt | http ]

http: error: ValueError: Invalid IPv6 URL
jay@JNET ~/Documents/Scripts/Medusa $ medusa -H target_ips.txt -U usernames.txt -P passwords.txt -M [ smbnt  ]
Medusa v2.2_rc3 [http://www.foofus.net] (C) JoMo-Kun / Foofus Networks <jmk@foofus.net>

IMPORTANT: Couldn't load "[" [/usr/lib/medusa/modules/[.mod: cannot open shared object file: No such file or directory]. Place the module in the medusa directory, set the MEDUSA_MODULE_NAME environment variable or run the configure script again using --with-default-mod-path=[path].
invokeModule failed - see previous errors for an explanation
jay@JNET ~/Documents/Scripts/Medusa $ medusa -H target_ips.txt -U usernames.txt -P passwords.txt -M [ http ]
Medusa v2.2_rc3 [http://www.foofus.net] (C) JoMo-Kun / Foofus Networks <jmk@foofus.net>

IMPORTANT: Couldn't load "[" [/usr/lib/medusa/modules/[.mod: cannot open shared object file: No such file or directory]. Place the module in the medusa directory, set the MEDUSA_MODULE_NAME environment variable or run the configure script again using --with-default-mod-path=[path].
invokeModule failed - see previous errors for an explanation

whats the module i need for rtsp / port 554 ???

**Comment by dru1d-foofus** [comment]
@jamieduk - The following command will list all available modules:
`medusa -d`

Unfortunately there is no RTSP module.

**Comment by jmk-foofus** [comment]
It looks like RTSP is basically HTTP with basic auth. The HTTP module might work for it, or might require minor tweaks. In either case, I don't have access to or plans to test against RTSP services. If someone else wants to and does the dev, feel free to submit a merge request.
