### ISSUE TITLE
http module returns wrong password

### ISSUE THREAD

**Issue by NathanSBurns** [jmk-foofus/medusa#25]
I am working on my OSCP and am trying to gain access to a phpmyadmin directory. However, an htaccess configuration requires a username and password before gaining access to the page. Medusa returns the first entry in the password list (which is invalid) and then exits. Any help would be greatl;y appreciated.

Command Executed: 
medusa -h 10.11.1.223 -P 1575-john.txt -u admin -M http -m DIR:phpmyadmin

Debug: 
Medusa v2.2 [http://www.foofus.net] (C) JoMo-Kun / Foofus Networks <jmk@foofus.net>

DEBUG [B6ABAAC0]: Successfully loaded login information.
DEBUG AUDIT [B6ABAAC0]: adding new server (0) to queue
DEBUG AUDIT [B6ABAAC0]: waiting for server pool to end
DEBUG SERVER [B6A0BB40]: Server ID: 0 Host: 10.11.1.223 iUserPassCnt: 71181 iLoginCnt: 1
DEBUG SERVER [B6A0BB40]: Set IPv4 address: 10.11.1.223 (10.11.1.223)
DEBUG SERVER [B6A0BB40]: Adding new login task (0) to server queue (0)
DEBUG SERVER [B6A0BB40]: waiting for server 0 login pool to end
DEBUG [B60FFB40]: startModule iId: 0 pLogin: B6A0B1E0 modParams->argv: 1D7D400 modParams: B6A0B1C0
DEBUG [B60FFB40]: Trying module path of .
DEBUG [B60FFB40]: Attempting to load ./http.mod
DEBUG [B60FFB40]: Trying module path of /usr/lib/i386-linux-gnu/medusa/modules
DEBUG [B60FFB40]: Attempting to load /usr/lib/i386-linux-gnu/medusa/modules/http.mod
DEBUG MODULE [B60FFB40]: OMG teh http.mod module has been called!!
DEBUG MODULE [B60FFB40]: Processing complete option: DIR:phpmyadmin
DEBUG MODULE [B60FFB40]: Processing option: DIR
DEBUG MODULE [B60FFB40]: Processing option parameter: phpmyadmin
DEBUG [B60FFB40]: [getNextNormalCred] Initial credential set request for login module.
DEBUG [B60FFB40]: [getNextNormalCred] (PARALLEL_LOGINS_PASSWORD) setting user: admin
DEBUG MODULE [B60FFB40]: [http.mod] module started for host: 10.11.1.223 user: admin
DEBUG [B60FFB40]: Connected (internal)
DEBUG MODULE [B60FFB40]: [http.mod] Sending initial non-authentication request: GET /phpmyadmin HTTP/1.1[0D][0A]Host: 10.11.1.223:80[0D][0A]User-Agent: Mozilla/1.22 (compatible; MSIE 10.0; Windows 3.1)[0D][0A][0D][0A]
DEBUG [B60FFB40]: Data sent: GET /phpmyadmin HTTP/1.1[0D][0A]Host: 10.11.1.223:80[0D][0A]User-Agent: Mozilla/1.22 (compatible; MSIE 10.0; Windows 3.1)[0D][0A][0D][0A]
DEBUG [B60FFB40]: Regural expession: "HTTP/1.* .*[0D][0A]"
DEBUG [B60FFB40]: Data receive: Data waiting.
DEBUG [B60FFB40]: Data received (764): HTTP/1.1 301 Moved Permanently[0D][0A]Date: Thu, 26 Apr 2018 10:11:56 GMT[0D][0A]Server: Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l mod_autoindex_color PHP/5.3.1 mod_apreq2-20090110/2.7.1 mod_perl/2.0.4 Perl/v5.10.1[0D][0A]Location: http://10.11.1.223/phpmyadmin/[0D][0A]Content-Length: 434[0D][0A]Content-Type: text/html; charset=iso-8859-1[0D][0A][0D][0A]<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">[0A]<html><head>[0A]<title>301 Moved Permanently</title>[0A]</head><body>[0A]<h1>Moved Permanently</h1>[0A]<p>The document has moved <a href="http://10.11.1.223/phpmyadmin/">here</a>.</p>[0A]<hr>[0A]<address>Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l mod_autoindex_color PHP/5.3.1 mod_apreq2-20090110/2.7.1 mod_perl/2.0.4 Perl/v5.10.1 Server at 10.11.1.223 Port 80</address>[0A]</body></html>[0A]
DEBUG [B60FFB40]: Formatted data received (size 764): HTTP/1.1 301 Moved Permanently[0D][0A]Date: Thu, 26 Apr 2018 10:11:56 GMT[0D][0A]Server: Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l mod_autoindex_color PHP/5.3.1 mod_apreq2-20090110/2.7.1 mod_perl/2.0.4 Perl/v5.10.1[0D][0A]Location: http://10.11.1.223/phpmyadmin/[0D][0A]Content-Length: 434[0D][0A]Content-Type: text/html; charset=iso-8859-1[0D][0A][0D][0A]<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">[0A]<html><head>[0A]<title>301 Moved Permanently</title>[0A]</head><body>[0A]<h1>Moved Permanently</h1>[0A]<p>The document has moved <a href="http://10.11.1.223/phpmyadmin/">here</a>.</p>[0A]<hr>[0A]<address>Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l mod_autoindex_color PHP/5.3.1 mod_apreq2-20090110/2.7.1 mod_perl/2.0.4 Perl/v5.10.1 Server at 10.11.1.223 Port 80</address>[0A]</body></html>[0A]
DEBUG [B60FFB40]: Successfully matched regex.
DEBUG MODULE [B60FFB40]: [http.mod] Parsing authentication header: HTTP/1.1 301 Moved Permanently[0D][0A]Date: Thu, 26 Apr 2018 10:11:56 GMT[0D][0A]Server: Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l mod_autoindex_color PHP/5.3.1 mod_apreq2-20090110/2.7.1 mod_perl/2.0.4 Perl/v5.10.1[0D][0A]Location: http://10.11.1.223/phpmyadmin/[0D][0A]Content-Length: 434[0D][0A]Content-Type: text/html; charset=iso-8859-1[0D][0A][0D][0A]<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">[0A]<html><head>[0A]<title>301 Moved Permanently</title>[0A]</head><body>[0A]<h1>Moved Permanently</h1>[0A]<p>The document has moved <a href="http://10.11.1.223/phpmyadmin/">here</a>.</p>[0A]<hr>[0A]<address>Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l mod_autoindex_color PHP/5.3.1 mod_apreq2-20090110/2.7.1 mod_perl/2.0.4 Perl/v5.10.1 Server at 10.11.1.223 Port 80</address>[0A]</body></html>[0A]
DEBUG MODULE [B60FFB40]: [http.mod] No authentication header located.
DEBUG [B60FFB40]: Disconnect successful
DEBUG [B60FFB40]: Connected (internal)
DEBUG MODULE [B60FFB40]: [http.mod] No authentication required.
ACCOUNT CHECK: [http] Host: 10.11.1.223 (1 of 1, 0 complete) User: admin (1 of 1, 0 complete) Password: 123456 (1 of 71181 complete)
ACCOUNT FOUND: [http] Host: 10.11.1.223 User: admin Password: 123456 [SUCCESS]
INFO: Login Module: 0 - Current user password list is complete, selecting next user.
INFO: Login Module: 0 - Current user password list is complete, rescanning userlist for unfinished credentials.
INFO: Login Module: 0 - Current user password list is complete, selecting next user.
INFO: Login Module: 0 - No more user accounts available for testing.
INFO: Login Module: 0 - No more users/passwords available in the normal queue.
DEBUG [B60FFB40]: Retrieving the next available credential set from list of previously missed sets.
INFO: Login Module: 0 - No additional missed users/passwords, setting credential status to CREDENTIAL_DONE.
DEBUG MODULE [B60FFB40]: [http.mod] No more available credential sets to test.
DEBUG [B60FFB40]: Disconnect successful
DEBUG SERVER [B6A0BB40]: destroying server 0 login pool
DEBUG SERVER [B6A0BB40]: exiting server: 0
DEBUG AUDIT [B6ABAAC0]: destroying server pool

**Comment by jmk-foofus** [comment]
The site was returning a redirect with a "/" at the end. It might have been as simple as adding that slash to the DIR variable in the Medusa call.
