### ISSUE TITLE
Couldn't load "rdp" 

### ISSUE THREAD

**Issue by SoftwareSinner** [jmk-foofus/medusa#29]
Having an issue trying to use the rdp module. 

command example: `medusa -M rdp -m DOMAIN:USER -h TARGET -u lockout -P '/root/Desktop/changemewordlist' 
`
```
Couldn't load "rdp" [/usr/lib/x86_64-linux-gnu/medusa/modules/rdp.mod: cannot open shared object file: No such file or directory]. Place the module in the medusa directory, set the MEDUSA_MODULE_NAME environment variable or run the configure script again using --with-default-mod-path=[path].
invokeModule failed - see previous errors for an explanation

```

I am using kali linux

**Comment by CRONN94** [comment]
> Having an issue trying to use the rdp module.
> 
> command example: `medusa -M rdp -m DOMAIN:USER -h TARGET -u lockout -P '/root/Desktop/changemewordlist' `
> 
> ```
> Couldn't load "rdp" [/usr/lib/x86_64-linux-gnu/medusa/modules/rdp.mod: cannot open shared object file: No such file or directory]. Place the module in the medusa directory, set the MEDUSA_MODULE_NAME environment variable or run the configure script again using --with-default-mod-path=[path].
> invokeModule failed - see previous errors for an explanation
> ```
> 
> I am using kali linux

Hi I have a similar problem. Did you find a solution?

**Comment by jmk-foofus** [comment]
Looks like the default build of Medusa on Kali doesn't include the RDP module. You'll need to build from source until that is resolved.
