### ISSUE TITLE
Error while make

### ISSUE THREAD

**Issue by joeldeleep** [jmk-foofus/medusa#30]
vnc.c:815:12: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
   dh_struct->g = BN_new(); 

above mentioned error is shown during the make 
i am using medua 2.2 which i downloaded from http://www.foofus.net/jmk/tools/medusa-2.2.tar.gz

**Comment by jmk-foofus** [comment]
Deprecated OpenSSL calls (e.g., DH) have been removed, so should no longer be an issue.
