### ISSUE TITLE
0x0002000C:UNKNOWN_ERROR_CODE

### ISSUE THREAD

**Issue by m0hammadhossein** [jmk-foofus/medusa#31]
Hello. 
 This problem occurs to me when cracking the VPS. It is also a list with any password list And the rest of the passwords are not checked
![screenshot from 2018-10-12 11-35-50](https://user-images.githubusercontent.com/19938015/46879102-1661aa80-ce13-11e8-8e11-7faf547a8300.png)

**Comment by jmk-foofus** [comment]
Not enough info to troubleshoot. I'd need to know target OS/configuration, whether FreeRDP works to connect, etc.
