### ISSUE TITLE
./configure: line 5801: syntax error near unexpected token 'FREERDP2'

### ISSUE THREAD

**Issue by slycooper166** [jmk-foofus/medusa#32]
I am trying to install medusa on windows using kali linux and I can't get the ./configure action to complete because it lists the error as follows:

./configure: line 5801: syntax error near unexpected token 'FREERDP2'
./configure: 'PKG_CHECK_MODULES(FREERDP2, freerdp2)'

**Comment by jmk-foofus** [comment]
Fixed in master.
