### ISSUE TITLE
Fedora's "medusa" package installs modules in "/usr/lib64/medusa/modules" folder but executable searchs them in "/usr/lib/medusa/modules"...

### ISSUE THREAD

**Issue by q2dg** [jmk-foofus/medusa#35]
...so it can't find any one. The solution is so easy as doing _ln -s /usr/lib64/medusa/modules /usr/lib/medusa/modules_ but it's a pity. Maybe it's just a problem of Fedora packaging, but I open this issue in case someone suffers the same problem.

**Comment by q2dg** [comment]
Well, it seems nobody cares.
Let's go to Hydra/Ncrack, then

**Comment by jmk-foofus** [comment]
Medusa builds from source and works on Fedora in my quick test. This feels like a packaging issue. I'm not a Fedora user, feel free to submit an update to their package.
