### ISSUE TITLE
RomSShell server it's error

### ISSUE THREAD

**Issue by sechacking** [jmk-foofus/medusa#4]
RomSShell server  auth it's error...

like ACCOUNT FOUND: [ssh] Host: x.x.x.x User: root Password: 123456a [SUCCESS]

medusa say success,that be wrong.

**Comment by jmk-foofus** [comment]
I need more information than this, if I'm going to troubleshoot. For example, debug output generated using "-v 99 -w 99". Information about the remote service is also helpful.

Please don't include public IP addresses in posts. You should have permission to be testing these devices. I certainly don't and I won't be connecting to them.
