### ISSUE TITLE
HTTP not working properly

### ISSUE THREAD

**Issue by helixxger** [jmk-foofus/medusa#43]
I'm trying to bruteforce a password via http with this command: 
medusa -h IPADDRESS -u USERNAME -P /home/USERNAME/Schreibtisch/darkweb2017-top1000.txt -M http

but it only tries the first password of 1000 and then it says: "ACCOUNT FOUND: [http] Host: IPADDRESS User: USERNAME Password: PASSWORD [SUCCESS]

But I tried, it's not the password.

What can I do?
See attachment

![Bildschirmfoto_2020-12-18_12-07-08](https://user-images.githubusercontent.com/76208371/102608387-16177500-412a-11eb-8079-e11807f581f1.png)

**Comment by bugith** [comment]
Same behaviour here v2.2
