### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by freetest** [jmk-foofus/medusa#5]
<img width="1277" alt="2015-11-25 10 26 34" src="https://cloud.githubusercontent.com/assets/5380255/11386717/185a29ee-935f-11e5-9a1e-c4ba29c5c400.png">

**Comment by jmk-foofus** [comment]
The Medusa RDP module is currently disabled on OS X. The configure script should have displayed that warning and skipped trying to build the module. I'm assuming you overrode its default behavior by forcing the module to be enabled with "--enable-module-rdp". This option is useful if you want to try and build it and debug the linking issue on OS X. I welcome a patch that resolves this problem. I don't foresee myself having time, or need, to address this specific issue in the near future.
