### ISSUE TITLE
Thread perallelize bug

### ISSUE THREAD

**Issue by xyzzklk** [jmk-foofus/medusa#54]
I use the command `medusa -H target.txt -U user.txt -P smallpass.txt -T 1 -t 3 -M ssh` to test some hosts. The file `target.txt` is a file that contains 2 IPs; the file `user.txt` contains 5 usernames; the file `smallpass.txt` contains 13 passwords.

I did't add the `-L` parameter, because I don't want each thread to test a username parallelly. I want all the threads to process an entire username before proceeding, one by one.
![IMG_20220203_171835](https://user-images.githubusercontent.com/90095370/152314437-65ee127e-9a34-404d-aab9-8aa214d7a883.jpg)
But, in this instance, after the first username `root` has been completely tested, the threads changed to be parallel, although i didn't add the `-L` parameter. 

Is this a default setting or a bug? Please help me, thank you very much.

**Comment by jmk-foofus** [comment]
Ancient bug... not sure how this has been missed all these years.
