### ISSUE TITLE
medusa fails on mssql module with Windows authentication mode

### ISSUE THREAD

**Issue by axzhandul** [jmk-foofus/medusa#55]
I am trying to use Medusa to brute-force MSSQL logins (disclaimer: authorized). Before running larger user and password lists, I am trying to verify accurate function against the SQL Server with a known username and password. Using the mssql module, I cannot get this to work correctly, although I know for a fact (both by connecting successfully and cracking successfully with other tools) these credentials work.

I believe the issue may be related to Windows authentication, which is the default for MSSQL and also the configuration setting of the server, meaning that my username requires a domain in addition to the password to successfully connect. I have tried all of the following forms of command to no avail (actual username, password, host, and port redacted).
```
medusa -h 10.10.10.51 -n 7777 -M mssql -u "DOMAIN\myusername" -p mypassword -v 6 -w 5
medusa -h 10.10.10.51 -n 7777 -M mssql -u DOMAIN\myusername -p mypassword -v 6 -w 5
medusa -h 10.10.10.51 -n 7777 -M mssql -u DOMAIN\\myusername -p mypassword -v 6 -w 5
medusa -h 10.10.10.51 -n 7777 -M mssql -u myusername@DOMAIN -p mypassword -v 6 -w 5
medusa -h 10.10.10.51 -n 7777 -M mssql -u myusername -p mypassword -v 6 -w 5
```

All of these commands result in the same similar output as below:
```
└─$ medusa -h 10.10.10.51 -n 7777 -M mssql -u "DOMAIN\myusername" -p mypassword -v 6 -w 5
Medusa v2.2 [http://www.foofus.net] (C) JoMo-Kun / Foofus Networks <jmk@foofus.net>

GENERAL: Parallel Hosts: 1 Parallel Logins: 1
GENERAL: Total Hosts: 1 
GENERAL: Total Users: 1
GENERAL: Total Passwords: 1
ACCOUNT CHECK: [mssql] Host: 10.10.10.51 (1 of 1, 0 complete) User: DOMAIN\myusername (1 of 1, 0 complete) Password: mypassword (1 of 1 complete)
GENERAL: Medusa has finished.
```

Below is my configuration information: 

- OS:
```
└─$ cat /etc/os-release                                       
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2021.4"
VERSION_ID="2021.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=Debbie
```

- Medusa version:
```
Medusa v2.2 [http://www.foofus.net] (C) JoMo-Kun / Foofus Networks <jmk@foofus.net>
```

- MS SQL SERVER:
```
Microsoft SQL Server 2014, 12.0.6433.1 (X64)
```

MSSQL supports three authentication modes: 

- Windows authentication only (default)
- SQL Server authentication only
- Mixed-mode authentication

I have not seen where in the documentation there is any discussion of what MSSQL authentication modes Medusa supports. If someone could give me a hand and let me know what Medusa supports / doesn't and how to get this working (if possible), it would be greatly appreciated -- thanks!

**Comment by jmk-foofus** [comment]
The MSSQL module only supports native SQL authentication. Windows integrated authentication support would be great, but I do not have plans at this time to implement it.

**Comment by axzhandul** [comment]
@jmk-foofus -- thx for the update, I totally understand, and if I had limited resource, it probably makes sense. However, for anyone that might find themselves with the bandwidth (er....the mythical "copious free time") to implement, I can give maybe a use-case which would make Windows auth support all the more valuable. 

I'd imagine that most use of the medusa mssql module is employed in the direct effort of trying to crack the mssql server itself. However, in offensive ops which might require stealth (red teaming) trying to crack AD account credentials by proxying brute force through mssql can fly under detection radar, b/c alerts might be tuned to ignore auth attempts coming from the mssql server. So my take is that supporting Windows auth may be a double-bonus. 

@jmk-foofus -- I dug into the source at the time, but if there's any recommended starting point you know for looking deeper into this, let me know, and I'll look into it, if you'd be open to a contribution. In any case, I really appreciate the response. Keep up the good work!
