### ISSUE TITLE
freerdp 1.2 not detected properly + incompatible (freerdp module not working)

### ISSUE THREAD

**Issue by anthraxx** [jmk-foofus/medusa#6]
Hey,

I have noticed that the RDP plugin does not work properly with an up-to-date freerdp. The configure detection seems to fail and HAVE_LIBFREERDP12 will not be defined and therefor tries to use freerdp_channels_global_init:

```
IMPORTANT: Couldn't load "rdp" [/usr/lib/medusa/modules/rdp.mod: undefined symbol: freerdp_channels_global_init].
```

the configure script fails to find WLog_CallbackAppender_SetCallbacks as that function does not exist in freerdp 1.2.0-beta1+android9 and also not in the current git HEAD.

```
configure: checking for FreeRDP library version 1.2...
checking for library containing WLog_CallbackAppender_SetCallbacks... no
configure: checking for FreeRDP library version 1.1 (with pass-the-hash)...
checking for library containing nego_set_restricted_admin_mode_required... none required
configure:  *** Detected FreeRDP library version 1.1 (with pass-the-hash). *** 
```

But as mentioned, its not just the detection of 1.2 but also the API changed and there is no Log_CallbackAppender_SetCallbacks function anymore in the current freerdp git HEAD (neither in the last tag 1.2.0-beta1+android9).

It would be great if the freerdp module works with the current git HEAD, i would highly appreciate that :smile: 
cheers,
anthraxx

**Comment by astro-train** [comment]
I am sorry, Is there any working solution for RDP checking? I looked up freerdp code but found no way to check wheter auth data was correct or not.

**Comment by anthraxx** [comment]
didn't they just renamed stuff? I'm pretty sure it has to be possible to check it one or the other way.
No time yet to search for that actually, but i really assume that its still possible as freerdp is a library :smile: 

Maybe try writing the authors an email (I would not just open an issue, they most likely will not notice that because of 200 other issues :crying_cat_face: )

**Comment by astro-train** [comment]
@anthraxx, I don't know, really, there's a lot of code and understanding of how it works will take a lot of time, but as far as I saw there's no definition of auth states and errors. Maybe they were in oldest versions?
Hm, what Is the best approach to write them? Something like "Hi, I'm writing RDP bruteforce tool and stuff, could you please rewrite code so I can be sure why login attempt failed. Cheers". I dont know if this is a good idea.

**Comment by anthraxx** [comment]
@astro-train maybe you don't have to mention that you write a bruteforce tool. just say you are writing a RDP (maybe GUI) tool that uses freerdp as a library and you want to check the authentication login state for success or different type of failed codes. Something like that :smile:

**Comment by astro-train** [comment]
@anthraxx, oh okay, but it still sounds like I'am writing bf.

**Comment by anthraxx** [comment]
is there really no other way doing this? It really sounds weird that its not possible to get a result of a login attempt. :sob:

**Comment by jmk-foofus** [comment]
There's talk on the FreeRDP mailing list of freezing the API later this summer and a release being in the foreseeable future. I'm planning to revisit the Medusa RDP module when that happens. FreeRDP has been too much of a moving target.

**Comment by anthraxx** [comment]
that sounds awesome :smile: 
a heads-up: maybe it will make sense to implement a way in the autoconf thingie to detect freerdp flags from pkg-config as the default import locations changed for freerdp 1.2:
```
> pkg-config --cflags freerdp2
-I/usr/include/freerdp2/ -I/usr/include/winpr2
```

so the header is f.e. in ```/usr/include/freerdp2/freerdp/freerdp.h```

**Comment by rhertzog** [comment]
@jmk-foofus In the mean time FreeRDP 1.x has gotten obsolete. Do you plan to port the code to version 2.x ? This is needed for the Debian package if we want to keep the RDP module enabled. See https://bugs.debian.org/888322

TIA.

**Comment by anthraxx** [comment]
same applies for Arch Linux, i was forced to not ship RDP module for now :cry:

**Comment by jmk-foofus** [comment]
I do plan to port the RDP module. Unfortunately, I do not have an estimated date for this.

 

Joe

**Comment by jmk-foofus** [comment]
RDP module in master should be working with current releases of FreeRDP.
