### ISSUE TITLE
Not showing password

### ISSUE THREAD

**Issue by wardfranssen** [jmk-foofus/medusa#60]
When I use Medusa it seems to work but when I open the log file I specified it does not tell me what password worked it just shows the file which I told it to take passwords from and try(in this case I am using rockyou.txt for the passwords). Please help me I am using kali linux via virtualbox.

**Comment by xyzzklk** [comment]
Could you provide more details? I'd like to see your actual log and commands so I can help you more.

**Comment by jmk-foofus** [comment]
Closing - not enough info.
