### ISSUE TITLE
can not auto finish

### ISSUE THREAD

**Issue by sechacking** [jmk-foofus/medusa#8]
99 hosts,option is -T 50 -c 2 -g 1 -R 1 -f

see debug log is

DEBUG [C83D9700]: Retrieving the next available credential set from list of previously missed sets.
INFO: Login Module: 0 - No additional missed users/passwords, setting credential status to CREDENTIAL_DONE.
DEBUG MODULE [C83D9700]: [ssh.mod] No more available credential sets to test.
DEBUG [C83D9700]: Disconnect successful
DEBUG SERVER [D19E8700]: destroying server 94 login pool
DEBUG SERVER [D19E8700]: exiting server: 94

may be ssh Handshake problem

so can add option to socket timeout?

**Comment by sechacking** [comment]
DEBUG [AD7FB700]: Disconnect successful
ERROR: Thread AD7FB700: Host: 192.168.11.1 Cannot connect [unreachable], retrying (1 of 1 retries)
NOTICE: ssh.mod: failed to connect, port 22 was not open on 192.168.11.1
DEBUG SERVER [BF5FE700]: destroying server 94 login pool
DEBUG SERVER [BF5FE700]: Server thread exiting and server's userlist testing was marked as in progress. Was this host prematurely aborted?
DEBUG SERVER [BF5FE700]: exiting server: 94

**Comment by bismark-foofus** [comment]
Closing, not enough information to debug.
