### ISSUE TITLE
medusa: ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.

### ISSUE THREAD

**Issue by zhangcaiyan** [jmk-foofus/medusa#9]
hello, friend, if many ips or passwords， I will have this question：

medusa: ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.

thank you!

**Comment by dean2020** [comment]
medusa: ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.
 还有人管吗？

**Comment by bismark-foofus** [comment]
Closing as not enough information to debug.
